"""Guard for bugs/0821 -- the 7-row penta cascade is derived, not stored.

User: "I think we only need five_penta_prism_analytic_telescope_cascade.py, the rest of the
five_penta can be retired", and then, about the file the whole penta suite loads:
"five_penta_prism_analytic_telescope_cascade.py got more than five_penta_prism_cascade.py."

Measured: the analytic telescope cascade carries 18 rows to the plain cascade's 7, and its first
six -- Object plus Penta prism 1..5 -- are BYTE-IDENTICAL to the plain cascade's. The only
difference is the tail, where the plain file stops at an Image row at the origin and the analytic
one continues into ball lenses, a DCV, an achromat and a cylindrical. So the plain cascade is the
analytic one's prism head plus an Image row, and keeping both stores the same geometry twice.

`ensure_five_penta_cascade` derives it on demand, so the file can be deleted and comes back
identical. Verified: deleted, regenerated by phase 0, penta phases 0-60 pass exactly as with the
stored fixture (60 pass, only the baseline-known phase 52 red).

Checks (SKIP when the Filen-synced attachment tree has neither file):
  A  the derived cascade is the source's prism head: 7 rows, the five prisms carrying their
     OpticalSolidFaces, an Image at the origin, and rows 0-5 equal to the source's field for field.
  B  the call is idempotent -- an existing fixture is returned untouched, not rewritten.
  C  no source and no fixture returns None rather than raising: every caller treats it as SKIP.
  D  the wiring: phase 0 and the five standalone consumers all ensure before they judge.

Run:
    xvfb-run -a .devenv/state/venv/bin/python -m KrakenOS.UI.validate_open3d_0821_the_cascade_is_a_recipe
"""
from __future__ import annotations

import inspect
import re
import tempfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SOURCE = PROJECT_ROOT / "attachment/five_penta_prism_analytic_telescope_cascade.py"
CASCADE = PROJECT_ROOT / "attachment/five_penta_prism_cascade.py"
EXPECTED_NAMES = ["Object", "Penta prism 1", "Penta prism 2", "Penta prism 3",
                  "Penta prism 4", "Penta prism 5", "Image"]
FIELDS = ("thickness", "diameter", "rc", "glass",
          "desp_x", "desp_y", "desp_z", "tilt_x", "tilt_y", "tilt_z")


def _rows(path: Path):
    text = Path(path).read_text(encoding="utf-8", errors="replace")
    out = []
    for block in re.findall(r"surfaces\.append\(\{.*?\}\)\n", text, re.S):
        row = {"name": (re.search(r"'name': '([^']*)'", block) or [None, "?"])[1],
               "solid": "OpticalSolidFaces" in block}
        for field in FIELDS:
            match = re.search(rf"'{field}': ([^,}}]*)", block)
            row[field] = match.group(1) if match else None
        out.append(row)
    return out


def _check_derivation(ok, skip) -> None:
    from KrakenOS.UI.services.penta_cascade_fixture import ensure_five_penta_cascade

    if not SOURCE.exists():
        skip("A/B: the analytic telescope cascade is not on this machine (Filen-synced)")
        return
    with tempfile.TemporaryDirectory() as tmp:
        target = Path(tmp) / "derived_five_penta_prism_cascade.py"
        result = ensure_five_penta_cascade(target, source=SOURCE)
        if result is None or not target.exists():
            skip("A: the derivation needs a Tk display and could not run here")
            return
        derived = _rows(target)
        source_rows = _rows(SOURCE)
        ok(
            [r["name"] for r in derived] == EXPECTED_NAMES,
            f"A1: the derived cascade is Object + five penta prisms + Image "
            f"({[r['name'] for r in derived]})",
        )
        ok(
            all(r["solid"] for r in derived[1:6]),
            "A2: every prism row keeps its OpticalSolidFaces (the vendor geometry, not a stub)",
        )
        head_matches = all(
            all(derived[i][f] == source_rows[i][f] for f in FIELDS) for i in range(6)
        )
        ok(
            head_matches,
            "A3: rows 0-5 match the analytic cascade field for field -- the derivation copies "
            "the prism head, it does not rebuild it",
        )
        image = derived[-1]
        ok(
            all(float(image[f] or 0.0) == 0.0 for f in ("desp_x", "desp_y", "desp_z",
                                                        "tilt_x", "tilt_y", "tilt_z")),
            f"A4: the Image row sits at the origin, where the plain cascade's always did "
            f"(desp {image['desp_x']}, {image['desp_y']}, {image['desp_z']})",
        )
        stamp = target.stat().st_mtime_ns
        again = ensure_five_penta_cascade(target, source=SOURCE)
        ok(
            again == target and target.stat().st_mtime_ns == stamp,
            "B1: an existing fixture is returned untouched -- the recipe never rewrites it",
        )


def _check_absent(ok) -> None:
    from KrakenOS.UI.services.penta_cascade_fixture import ensure_five_penta_cascade

    with tempfile.TemporaryDirectory() as tmp:
        target = Path(tmp) / "nowhere.py"
        missing_source = Path(tmp) / "no_source.py"
        try:
            value = ensure_five_penta_cascade(target, source=missing_source)
            raised = False
        except Exception:
            value, raised = "raised", True
        ok(
            not raised and value is None and not target.exists(),
            f"C1: with neither fixture nor source it returns None and writes nothing "
            f"({'raised' if raised else value})",
        )


def _check_wiring(ok) -> None:
    import KrakenOS.UI.validate_open3d_penta_telescope_comprehensive as penta

    src = inspect.getsource(penta.phase_0_load_cascade) if hasattr(penta, "phase_0_load_cascade") else ""
    if not src:
        src = Path(penta.__file__).read_text(encoding="utf-8")
    ok(
        "ensure_five_penta_cascade" in src,
        "D1: penta phase 0 derives the fixture instead of failing on its absence",
    )
    consumers = (
        "validate_open3d_penta_telescope_chain",
        "validate_open3d_penta_cascade_prism_by_prism",
        "validate_open3d_five_penta_initial_visual",
        "validate_optical_solid_face_coating",
        "validate_open3d_0485_axis_fold_emissions",
    )
    missing = [
        name for name in consumers
        if "ensure_five_penta_cascade" not in
        (PROJECT_ROOT / "KrakenOS" / "UI" / f"{name}.py").read_text(encoding="utf-8")
    ]
    ok(
        not missing,
        f"D2: every standalone consumer of the cascade ensures it first ({len(consumers)} "
        f"modules{'' if not missing else '; missing: ' + ', '.join(missing)})",
    )


def run_checks(verbose: bool = False, app=None, inspector=None) -> "tuple[bool, list[str]]":
    notes: list[str] = []

    def ok(cond: bool, label: str) -> None:
        notes.append(("PASS " if cond else "FAIL ") + label)

    def skip(label: str) -> None:
        notes.append("SKIP " + label)

    _check_derivation(ok, skip)
    _check_absent(ok)
    _check_wiring(ok)

    passed = not any(n.startswith("FAIL") for n in notes)
    if verbose:
        for n in notes:
            print(n)
    return passed, notes


def main() -> int:
    passed, notes = run_checks(verbose=True)
    if passed:
        print("Open 3D penta-cascade recipe validation passed.")
        return 0
    print("Open 3D penta-cascade recipe validation FAILED:")
    for n in notes:
        if n.startswith("FAIL"):
            print(f"- {n}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
