"""Captions shared by the SVG and reStructuredText generators."""

TOPICS = {
    "1-1": "A translated pulse keeps its shape: positive and negative phase signs select opposite propagation directions.",
    "1-2": "Spatial and temporal sections of a sinusoid distinguish wavelength from period; the time trace uses Problem 1.43.",
    "1-3": "Constant-phase trajectories have slope equal to phase velocity. A larger phase offset shifts a crest without changing its speed.",
    "1-4": "Complex amplitudes add as vectors. The resultant's length and argument determine amplitude and phase.",
    "1-5": "Parallel phase planes describe a plane wave; concentric phase circles are sections of spherical wavefronts.",
    "2-1": "Electric field, magnetic field, and propagation direction are mutually perpendicular in a vacuum plane wave.",
    "2-2": "An interface preserves frequency while changing speed and wavelength. The example compares indices 1 and 1.5.",
    "2-3": "Irradiance follows the time average of the squared field, not the average field itself.",
    "2-4": "Absorption transfers one photon momentum; reversal by an ideal mirror transfers twice that momentum.",
    "2-5": "Photon energy decreases as wavelength increases. The visible band occupies only a small portion of this logarithmic scale.",
    "3-1": "Refraction through a parallel plate restores the original direction but leaves a perpendicular lateral displacement.",
    "3-2": "Fermat's stationary optical path selects the interface crossing that satisfies Snell's law.",
    "3-3": "Air-to-glass Fresnel power reflectances differ for s and p light; the p curve vanishes at the Brewster angle.",
    "3-4": "Glass-to-air reflection becomes total beyond the critical angle. Both polarization power reflectances then equal one.",
    "4-1": "Equal optical paths define a Cartesian oval. The plotted interface focuses a real axial source into a second medium.",
    "4-2": "Spherical-interface conjugates depend on the incident and transmitted indices and the signed radius of curvature.",
    "4-3": "A positive thin lens forms a real inverted image when the object is outside its front focal point.",
    "4-4": "Sequential paraxial tracing for Problem 4.80: the second lens intercepts a converging bundle and moves its final focus farther away.",
    "4-5": "Problem 4.82: principal planes lie inside the thick lens, so effective and vertex focal distances are different.",
    "4-6": "Huygens and Ramsden oculars have different front focal-plane positions despite both producing collimated output.",
    "4-7": "Problem 4.94: rays from the object meet at a real, inverted, half-height mirror image.",
    "5-1": "Linear polarization is a fixed transverse direction multiplied by one oscillating scalar amplitude.",
    "5-2": "Opposite circular states trace the same circle but rotate in opposite directions at a fixed observation point.",
    "5-3": "Relative phase and component amplitudes determine the ellipse orientation and the ratio of its principal axes.",
    "5-4": "Problem 5.66: the analyzer scan separates a polarized contribution from an angle-independent unpolarized background.",
    "5-5": "Successive Malus projections explain why intermediate polarizers transmit light between crossed end polarizers.",
    "5-6": "At Brewster incidence the p reflection vanishes, and the reflected and transmitted ray directions are perpendicular.",
    "5-7": "A quarter-wave plate changes the phase relation between eigenaxis components; a half-wave plate reverses circular handedness.",
    "6-1": "Two-source array factors show how spacing creates extra lobes and a relative phase steers them.",
    "6-2": "Two coherent source images produce alternating bright and dark screen positions according to their path difference.",
    "6-3": "The thin-film round trip adds propagation phase; a single reflection reversal interchanges reflected maxima and minima.",
    "6-4": "A Michelson mirror displacement changes optical path twice as much, explaining the factor of two in fringe counting.",
    "6-5": "Finite spectral width limits fringe visibility as optical delay grows. The plotted Gaussian envelope is illustrative, not a universal line shape.",
    "7-1": "Increasing the coherent element count narrows principal peaks and inserts more subsidiary maxima and zeros.",
    "7-2": "A double-slit interference factor is modulated by its single-slit envelope; missing orders occur at envelope zeros.",
    "7-3": "The grating equation separates wavelengths by angle, while finite illuminated line count limits resolution.",
    "7-4": "Rectangular pupils give separable sinc patterns; circular pupils give an Airy pattern with its first zero at 1.22 wavelength over diameter.",
    "7-5": "Circular-aperture axial irradiance oscillates with the exposed Fresnel-zone count rather than increasing monotonically with radius.",
    "7-6": "The complex field is a chord of the Cornu spiral. A straight edge gives one quarter of unobstructed irradiance at the shadow boundary.",
    "8-1": "Fourier partial sums reconstruct the ramp/step waveform and the triangular waveform from their independently calculated coefficients.",
    "8-2": "A rectangular window transforms to a sinc; a Gaussian transforms to a Gaussian without the ideal sinc's sidelobes.",
    "8-3": "Convolution adds positions and multiplies weights. Three unit impulses produce the five-weight sequence 1, 2, 3, 2, 1.",
}

PROBLEMS = {
    "6.52": "The literal perpendicular bisector has equal paths everywhere. The printed numerical endpoint instead uses a line through one source.",
    "7.61": "The single-slit half-irradiance crossings give a full width of 0.885893 wavelength times distance divided by slit width.",
    "7.89": "Zone-sector aperture for Problem 7.89: the whole first zone and one quarter of the second zone are open.",
    "7.91": "Two semicircular openings end at the first and third Fresnel-zone boundaries; their on-axis amplitudes reinforce.",
    "7.92": "The blocked first zone plus half the second zone has the same axial field as the unobstructed beam; their difference is nearly zero.",
    "7.100": "The largest axial slit irradiance occurs at scaled half-width 1.20938; subsequent width oscillations tend toward the unobstructed value.",
    "7.105": "Numerical Fresnel propagation behind the specified opaque strip shows the weak central irradiance and oscillatory lit-side fringes.",
    "8.42": "All sixteen ordered sums of four spectral positions give nine distinct output positions with the displayed multiplicities.",
    "8.43": "A rectangle convolved with an opposite-sign impulse pair becomes a bipolar rectangle with zero total area.",
    "8.44": "Self-convolution of two finite slits creates three triangular components, including two coincident cross terms at the centre.",
    "8.45": "The overlap length of unequal rectangles grows, plateaus, then decreases, producing a trapezoid rather than a triangle.",
    "8.46": "Shifted weighted triangular kernels add to the piecewise-linear interpolation of the impulse weights.",
    "8.47": "The six-hole mask has nineteen distinct pair-sum centres. Labels give convolution multiplicities, not physical hole diameters.",
}


def figure_name(key: str) -> str:
    return f"schaum_{key.replace('.', '_').replace('-', '_topic_')}.svg"
