TITLE = "Beam Splitter Two Arm Doublets"

SETTINGS = {
    "object_mode": "Infinity",
    "display_orientation": "Vertical",
    "wavelength": "0.55",
    "ray_count": "9",
    "ray_height_factor": "0.85",
    "source_model": "Collimated disk source",
    "source_radius": "5.0",
    "source_cone_angle": "0.0",
    "source_power": "1.0",
    "source_seed": "3",
    "source_x": "0.0",
    "source_y": "0.0",
    "source_z": "0.0",
    "source_angular_weight": "Uniform solid angle",
    "field_type": "Angle",
    "field_value": "0.0",
    "field_count": "1",
    "aperture_type": "EPD",
    "aperture_value": "16.0",
    "trace_mode": "Non-Sequential Preview",
    "nonseq_target_surface": "Auto",
    "nonseq_ns_limit": "160",
    "nonseq_energy_probability": False,
    "spot_view_mode": "Grid",
    "analysis_modes": ["spot"],
}

BEAM_SPLITTER_SETTINGS = {
    "split_mode": "Deterministic branches",
    "reflectance": 0.5,
    "absorption": 0.0,
    "transmit_phase_deg": 0.0,
    "reflect_phase_deg": 180.0,
    "min_branch_power": 1e-3,
    "max_branch_depth": 8,
}


def element_metadata(
    element_id,
    element_name,
    arm_role,
    *,
    parent_splitter="",
    branch_selector="",
    arm_distance=0.0,
):
    return {
        "element_id": element_id,
        "element_name": element_name,
        "arm_role": arm_role,
        "parent_splitter": parent_splitter,
        "branch_selector": branch_selector,
        "arm_distance": arm_distance,
        "local_decenter_x": 0.0,
        "local_decenter_y": 0.0,
        "local_tilt_x": 0.0,
        "local_tilt_y": 0.0,
        "local_tilt_z": 0.0,
    }


COMMON_SPLITTER = element_metadata("BS1", "Splitter", "Common")
TRANSMIT_DOUBLET = element_metadata(
    "TX_DBL",
    "Transmit doublet",
    "Transmit",
    parent_splitter="BS1",
    branch_selector="transmit",
    arm_distance=33.0,
)
TRANSMIT_DETECTOR = element_metadata(
    "TX_DET",
    "Transmit detector",
    "Detector",
    parent_splitter="BS1",
    branch_selector="transmit",
    arm_distance=95.0,
)
REFLECT_DOUBLET = element_metadata(
    "RX_DBL",
    "Reflect doublet",
    "Reflect",
    parent_splitter="BS1",
    branch_selector="reflect",
    arm_distance=25.0,
)
REFLECT_DETECTOR = element_metadata(
    "RX_DET",
    "Reflect detector",
    "Detector",
    parent_splitter="BS1",
    branch_selector="reflect",
    arm_distance=85.0,
)

# The splitter is a tilted 3 mm BK7 plate. The transmitted chief ray exits the
# parallel plate parallel to +Z but shifted to y ~= -0.710725 mm. The reflected
# chief ray travels along +Y from the splitter front surface. Decenter values
# below place real surfaces on those two arms while keeping one canonical
# KrakenOS surface table.
SURFACES = [
    {
        "surface": "Object",
        "name": "Input reference",
        "rc": 0.0,
        "thickness": 45.0,
        "diameter": 35.0,
        "glass": "AIR",
    },
    {
        "element": "Splitter",
        "surface": "Beam Splitter",
        "name": "50/50 splitter front",
        "rc": 0.0,
        "k": 0.0,
        "thickness": 3.0,
        "diameter": 35.0,
        "tilt_x": 45.0,
        "tilt_y": 0.0,
        "tilt_z": 0.0,
        "desp_x": 0.0,
        "desp_y": 0.0,
        "desp_z": 0.0,
        "axis_move": 0.0,
        "glass": "BK7",
        "advanced": {
            "BeamSplitter": BEAM_SPLITTER_SETTINGS,
            "Element": COMMON_SPLITTER,
        },
    },
    {
        "element": "Splitter",
        "surface": "Standard",
        "name": "Splitter rear face",
        "rc": 0.0,
        "k": 0.0,
        "thickness": 30.0,
        "diameter": 35.0,
        "tilt_x": 45.0,
        "tilt_y": 0.0,
        "tilt_z": 0.0,
        "desp_x": 0.0,
        "desp_y": 0.0,
        "desp_z": 0.0,
        "axis_move": 0.0,
        "glass": "AIR",
        "advanced": {"Element": COMMON_SPLITTER},
    },
    {
        "element": "Transmit doublet",
        "surface": "Standard",
        "name": "Transmit doublet crown front",
        "rc": 92.8470657,
        "k": 0.0,
        "thickness": 6.0,
        "diameter": 30.0,
        "desp_y": -0.710725,
        "glass": "BK7",
        "advanced": {"Element": TRANSMIT_DOUBLET},
    },
    {
        "element": "Transmit doublet",
        "surface": "Standard",
        "name": "Transmit doublet flint front",
        "rc": -30.7160867,
        "k": 0.0,
        "thickness": 3.0,
        "diameter": 30.0,
        "desp_y": -0.710725,
        "glass": "F2",
        "advanced": {"Element": TRANSMIT_DOUBLET},
    },
    {
        "element": "Transmit doublet",
        "surface": "Standard",
        "name": "Transmit doublet flint back",
        "rc": -78.19730726,
        "k": 0.0,
        "thickness": 48.0,
        "diameter": 30.0,
        "desp_y": -0.710725,
        "glass": "AIR",
        "advanced": {"Element": TRANSMIT_DOUBLET},
    },
    {
        "element": "Transmit detector",
        "surface": "Standard",
        "name": "Transmit arm detector",
        "rc": 0.0,
        "k": 0.0,
        "thickness": 0.0,
        "diameter": 45.0,
        "desp_y": -0.710725,
        "desp_z": 5.0,
        "glass": "AIR",
        "advanced": {"Element": TRANSMIT_DETECTOR},
    },
    {
        "element": "Reflect doublet",
        "surface": "Standard",
        "name": "Reflect doublet crown front",
        "rc": 92.8470657,
        "k": 0.0,
        "thickness": 6.0,
        "diameter": 30.0,
        "tilt_x": -90.0,
        "desp_y": 70.0,
        "desp_z": -90.0,
        "glass": "BK7",
        "advanced": {"Element": REFLECT_DOUBLET},
    },
    {
        "element": "Reflect doublet",
        "surface": "Standard",
        "name": "Reflect doublet flint front",
        "rc": -30.7160867,
        "k": 0.0,
        "thickness": 3.0,
        "diameter": 30.0,
        "tilt_x": -90.0,
        "desp_y": 76.0,
        "desp_z": -96.0,
        "glass": "F2",
        "advanced": {"Element": REFLECT_DOUBLET},
    },
    {
        "element": "Reflect doublet",
        "surface": "Standard",
        "name": "Reflect doublet flint back",
        "rc": -78.19730726,
        "k": 0.0,
        "thickness": 48.0,
        "diameter": 30.0,
        "tilt_x": -90.0,
        "desp_y": 79.0,
        "desp_z": -99.0,
        "glass": "AIR",
        "advanced": {"Element": REFLECT_DOUBLET},
    },
    {
        "element": "Reflect detector",
        "surface": "Standard",
        "name": "Reflect arm detector",
        "rc": 0.0,
        "k": 0.0,
        "thickness": 0.0,
        "diameter": 45.0,
        "tilt_x": -90.0,
        "desp_y": 130.0,
        "desp_z": -147.0,
        "glass": "AIR",
        "advanced": {"Element": REFLECT_DETECTOR},
    },
    {
        "surface": "Image",
        "name": "Global diagnostic image",
        "rc": 0.0,
        "thickness": 0.0,
        "diameter": 160.0,
        "glass": "AIR",
    },
]
