TITLE = "Beam Splitter 50/50 Example"

SETTINGS = {
    "object_mode": "Infinity",
    "display_orientation": "Vertical",
    "wavelength": "0.55",
    "ray_count": "25",
    "ray_height_factor": "0.85",
    "source_model": "Collimated disk source",
    "source_radius": "8.0",
    "source_cone_angle": "0.0",
    "source_power": "1.0",
    "source_seed": "3",
    "source_x": "0.0",
    "source_y": "0.0",
    "source_z": "0.0",
    "source_angular_weight": "Uniform solid angle",
    "field_type": "Angle",
    "field_value": "0.0",
    "field_count": "1",
    "aperture_type": "EPD",
    "aperture_value": "18.0",
    "trace_mode": "Non-Sequential Preview",
    "nonseq_target_surface": "Auto",
    "nonseq_ns_limit": "120",
    "nonseq_energy_probability": False,
    "spot_view_mode": "Grid",
    "analysis_modes": ["spot"],
}

BEAM_SPLITTER_SETTINGS = {
    "split_mode": "Deterministic branches",
    "reflectance": 0.5,
    "absorption": 0.0,
    "transmit_phase_deg": 0.0,
    "reflect_phase_deg": 180.0,
    "min_branch_power": 1e-3,
    "max_branch_depth": 8,
}

SURFACES = [
    {
        "surface": "Object",
        "name": "Input reference",
        "rc": 0.0,
        "thickness": 45.0,
        "diameter": 30.0,
        "glass": "AIR",
    },
    {
        "element": "Splitter",
        "surface": "Beam Splitter",
        "name": "50/50 coated front face",
        "rc": 0.0,
        "k": 0.0,
        "thickness": 3.0,
        "diameter": 25.0,
        "tilt_x": 45.0,
        "tilt_y": 0.0,
        "tilt_z": 0.0,
        "desp_x": 0.0,
        "desp_y": 0.0,
        "desp_z": 0.0,
        "axis_move": 0.0,
        "glass": "BK7",
        "advanced": {
            "BeamSplitter": BEAM_SPLITTER_SETTINGS,
            "Element": {
                "element_id": "BS1",
                "element_name": "Splitter",
                "arm_role": "Common",
                "parent_splitter": "",
                "branch_selector": "",
                "arm_distance": 0.0,
                "local_decenter_x": 0.0,
                "local_decenter_y": 0.0,
                "local_tilt_x": 0.0,
                "local_tilt_y": 0.0,
                "local_tilt_z": 0.0,
            },
            "Note": (
                "This front face deterministically spawns reflected and transmitted branches. "
                "Glass=BK7 and Thickness=3 mm model substrate propagation to the following rear AIR face."
            ),
        },
    },
    {
        "element": "Splitter",
        "surface": "Standard",
        "name": "BK7 plate rear face",
        "rc": 0.0,
        "k": 0.0,
        "thickness": 60.0,
        "diameter": 25.0,
        "tilt_x": 45.0,
        "tilt_y": 0.0,
        "tilt_z": 0.0,
        "desp_x": 0.0,
        "desp_y": 0.0,
        "desp_z": 0.0,
        "axis_move": 0.0,
        "glass": "AIR",
        "advanced": {
            "Element": {
                "element_id": "BS1",
                "element_name": "Splitter",
                "arm_role": "Common",
                "parent_splitter": "",
                "branch_selector": "",
                "arm_distance": 0.0,
                "local_decenter_x": 0.0,
                "local_decenter_y": 0.0,
                "local_tilt_x": 0.0,
                "local_tilt_y": 0.0,
                "local_tilt_z": 0.0,
            },
            "Note": "Rear surface exits the transmitted branch from BK7 back to air. Use the same TiltX as the front face for a parallel plate in the UI table.",
        },
    },
    {
        "surface": "Image",
        "name": "Large diagnostic target",
        "rc": 0.0,
        "thickness": 0.0,
        "diameter": 100.0,
        "glass": "AIR",
    },
]
