TITLE = "Cooke Triplet Optimization Case Study"

SETTINGS = {
    "object_mode": "Infinity",
    "display_orientation": "Vertical",
    "wavelength": "0.55",
    "ray_count": "25",
    "ray_height_factor": "0.8",
    "analysis_surface": "Auto",
    "aperture_type": "EPD",
    "aperture_value": "4.0",
    "field_type": "Angle",
    "field_value": "3.0",
    "field_count": "2",
    "spot_view_mode": "Grid",
    "image_diameter_mode": "Manual",
    "show_clipped_rays": True,
    "show_cardinals": True,
    "show_physical_distances": True,
    "analysis_mode": "none",
    "analysis_modes": [],
    "layout_preview_mode": "none",
    "auto_save_plot": False,
    "optimization_workers": "Auto",
    "selected_operands": ["Spot RMS", "MTF @ freq"],
    "operands": {
        "Spot RMS": {
            "weight": "1",
            "target": "0",
            "wavelength": "0.55",
            "field": "0",
            "surface": "Auto",
        },
        "MTF @ freq": {
            "weight": "0.5",
            "target": "0.35",
            "wavelength": "0.55",
            "field": "3",
            "field_x": "0",
            "field_y": "3",
            "surface": "Auto",
            "frequency": "20",
            "mtf_mode": "Average",
            "mtf_algorithm": "PSF FFT",
        },
    },
}

RADIUS_BOUNDS = {
    "S1": (15.0, 80.0),
    "S2": (-800.0, -20.0),
    "S3": (-80.0, -10.0),
    "S4": (10.0, 80.0),
    "S5": (20.0, 800.0),
    "S6": (-80.0, -10.0),
}

THICKNESS_BOUNDS = {
    "S2": (1.0, 12.0),
    "S4": (1.0, 10.0),
    "S6": (25.0, 70.0),
}


def _surface(
    *,
    name: str,
    rc: float,
    thickness: float,
    glass: str,
    element: str = "",
    diameter: float = 16.0,
    optimize_rc: bool = False,
    optimize_rc_bounds=None,
    optimize_thickness: bool = False,
    optimize_thickness_bounds=None,
) -> dict[str, object]:
    return {
        "surface": "Standard",
        "name": name,
        "rc": rc,
        "thickness": thickness,
        "diameter": diameter,
        "tilt_x": 0.0,
        "tilt_y": 0.0,
        "tilt_z": 0.0,
        "desp_x": 0.0,
        "desp_y": 0.0,
        "desp_z": 0.0,
        "axis_move": 0.0,
        "glass": glass,
        "element": element,
        "optimize_rc": optimize_rc,
        "optimize_rc_bounds": optimize_rc_bounds,
        "optimize_thickness": optimize_thickness,
        "optimize_thickness_bounds": optimize_thickness_bounds,
    }


SURFACES = [
    {
        "surface": "Object",
        "name": "Object at infinity",
        "rc": 0.0,
        "thickness": 100.0,
        "diameter": 100.0,
        "glass": "AIR",
        "element": "",
        "optimize_rc": False,
        "optimize_rc_bounds": None,
        "optimize_thickness": False,
        "optimize_thickness_bounds": None,
    },
    _surface(
        name="S1 Crown front",
        rc=1000.0,
        thickness=4.0,
        glass="SK16",
        element="Front crown",
        optimize_rc=True,
        optimize_rc_bounds=RADIUS_BOUNDS["S1"],
    ),
    _surface(
        name="S2 Crown back / air gap",
        rc=-1000.0,
        thickness=5.0,
        glass="AIR",
        element="Front crown",
        optimize_rc=True,
        optimize_rc_bounds=RADIUS_BOUNDS["S2"],
        optimize_thickness=True,
        optimize_thickness_bounds=THICKNESS_BOUNDS["S2"],
    ),
    _surface(
        name="S3 Flint front",
        rc=-1000.0,
        thickness=4.0,
        glass="F2",
        element="Center flint",
        optimize_rc=True,
        optimize_rc_bounds=RADIUS_BOUNDS["S3"],
    ),
    _surface(
        name="S4 Flint back / stop-side gap",
        rc=1000.0,
        thickness=5.0,
        glass="AIR",
        element="Center flint",
        optimize_rc=True,
        optimize_rc_bounds=RADIUS_BOUNDS["S4"],
        optimize_thickness=True,
        optimize_thickness_bounds=THICKNESS_BOUNDS["S4"],
    ),
    _surface(
        name="S5 Rear crown front",
        rc=1000.0,
        thickness=4.0,
        glass="SK16",
        element="Rear crown",
        optimize_rc=True,
        optimize_rc_bounds=RADIUS_BOUNDS["S5"],
    ),
    _surface(
        name="S6 Rear crown back / image gap",
        rc=-1000.0,
        thickness=50.0,
        glass="AIR",
        element="Rear crown",
        optimize_rc=True,
        optimize_rc_bounds=RADIUS_BOUNDS["S6"],
        optimize_thickness=True,
        optimize_thickness_bounds=THICKNESS_BOUNDS["S6"],
    ),
    {
        "surface": "Image",
        "name": "Image plane",
        "rc": 0.0,
        "thickness": 0.0,
        "diameter": 100.0,
        "glass": "AIR",
        "element": "",
        "optimize_rc": False,
        "optimize_rc_bounds": None,
        "optimize_thickness": False,
        "optimize_thickness_bounds": None,
    },
]
OPTIMIZED_SURFACES = [
    {
        **SURFACES[0],
        "name": "Object at infinity",
        "optimize_rc": False,
        "optimize_thickness": False,
    },
    _surface(
        name="S1 Crown front",
        rc=22.01359,
        thickness=3.25896,
        glass="SK16",
        element="Front crown",
        optimize_rc=True,
        optimize_rc_bounds=RADIUS_BOUNDS["S1"],
    ),
    _surface(
        name="S2 Crown back / air gap",
        rc=-435.76044,
        thickness=6.00755,
        glass="AIR",
        element="Front crown",
        optimize_rc=True,
        optimize_rc_bounds=RADIUS_BOUNDS["S2"],
        optimize_thickness=True,
        optimize_thickness_bounds=THICKNESS_BOUNDS["S2"],
    ),
    _surface(
        name="S3 Flint front",
        rc=-22.21328,
        thickness=0.99997,
        glass="F2",
        element="Center flint",
        optimize_rc=True,
        optimize_rc_bounds=RADIUS_BOUNDS["S3"],
    ),
    _surface(
        name="S4 Flint back / stop-side gap",
        rc=20.29192,
        thickness=4.75041,
        glass="AIR",
        element="Center flint",
        optimize_rc=True,
        optimize_rc_bounds=RADIUS_BOUNDS["S4"],
        optimize_thickness=True,
        optimize_thickness_bounds=THICKNESS_BOUNDS["S4"],
    ),
    _surface(
        name="S5 Rear crown front",
        rc=79.68360,
        thickness=2.95208,
        glass="SK16",
        element="Rear crown",
        optimize_rc=True,
        optimize_rc_bounds=RADIUS_BOUNDS["S5"],
    ),
    _surface(
        name="S6 Rear crown back / image gap",
        rc=-18.39533,
        thickness=42.20778,
        glass="AIR",
        element="Rear crown",
        optimize_rc=True,
        optimize_rc_bounds=RADIUS_BOUNDS["S6"],
        optimize_thickness=True,
        optimize_thickness_bounds=THICKNESS_BOUNDS["S6"],
    ),
    {
        **SURFACES[-1],
        "name": "Image plane",
        "optimize_rc": False,
        "optimize_thickness": False,
    },
]
