TITLE = "Galvo F-Theta Laser Scanner"

SETTINGS = {
    "layout_role": "system",
    "object_mode": "Finite",
    "display_orientation": "Vertical",
    "wavelength": "1.064",
    "ray_count": "9",
    "ray_height_factor": "0.8",
    "source_model": "Gaussian beam",
    "gaussian_input_mode": "Diameter + divergence",
    "gaussian_beam_diameter": "1.0",
    "gaussian_full_divergence": "50.0",
    "gaussian_waist_side": "Waist before source",
    "gaussian_m2": "1.1",
    "source_power": "1.0",
    "source_x": "0.0",
    "source_y": "0.0",
    "source_z": "0.0",
    "source_l": "0.0",
    "source_m": "0.0",
    "source_n": "1.0",
    "field_type": "Object Height",
    "field_value": "0.0",
    "field_count": "1",
    "aperture_type": "EPD",
    "aperture_value": "10.0",
    "trace_mode": "Folded Preview",
    "analysis_modes": ["spot"],
}

SURFACES = [
    {
        "surface": "Object",
        "element": "Laser source",
        "name": "1064 nm laser source plane",
        "rc": 0.0,
        "thickness": 50.0,
        "diameter": 12.0,
        "glass": "AIR",
    },
    {
        "surface": "Standard",
        "element": "Beam expander L1",
        "name": "Beam expander negative lens front",
        "rc": -24.0,
        "thickness": 3.0,
        "diameter": 12.0,
        "glass": "BK7",
    },
    {
        "surface": "Standard",
        "element": "Beam expander L1",
        "name": "Beam expander negative lens back",
        "rc": 24.0,
        "thickness": 70.0,
        "diameter": 12.0,
        "glass": "AIR",
    },
    {
        "surface": "Standard",
        "element": "Beam expander L2",
        "name": "Beam expander positive lens front",
        "rc": 90.0,
        "thickness": 4.0,
        "diameter": 28.0,
        "glass": "BK7",
    },
    {
        "surface": "Standard",
        "element": "Beam expander L2",
        "name": "Beam expander positive lens back",
        "rc": -90.0,
        "thickness": 90.0,
        "diameter": 28.0,
        "glass": "AIR",
    },
    {
        "surface": "Mirror",
        "element": "Galvo mirror",
        "name": "45 deg galvo fold mirror",
        "rc": 0.0,
        "thickness": 75.0,
        "diameter": 35.0,
        "tilt_x": 45.0,
        "axis_move": 2.0,
        "glass": "MIRROR",
        "advanced": {
            "Display2D": {
                "tilt_x_overlay_deg": [40.0, 45.0, 50.0],
            },
        },
    },
    {
        "surface": "Standard",
        "element": "F-theta proxy lens",
        "name": "F-theta proxy lens front",
        "rc": 125.0,
        "thickness": 8.0,
        "diameter": 50.0,
        "glass": "BK7",
    },
    {
        "surface": "Standard",
        "element": "F-theta proxy lens",
        "name": "F-theta proxy lens back",
        "rc": -125.0,
        "thickness": 130.0,
        "diameter": 50.0,
        "glass": "AIR",
    },
    {
        "surface": "Image",
        "element": "Scan plane",
        "name": "Flat scan/focus plane",
        "rc": 0.0,
        "thickness": 0.0,
        "diameter": 60.0,
        "glass": "AIR",
    },
]
