"""Machine-vision lens surrogate generated by folder import."""

# Auto-generated machine-vision lens surrogate (folder import, item 3).
#
# Source prescription : 0703-005-000-40-EXC.pdf
# Mechanical STEP     : attachment/Lens/0703-005-000-40-EXC/0703-005-000-40_PA_a_STEP.stp
# Datasheet PDF       : 0703-005-000-40-EXC.pdf
#
# This is NOT the vendor prescription -- it is a first-order paraxial
# blackbox (two ideal Thin-Lens groups + stop between Front/Rear Optical
# Vertex Datums) solved from KrakenOS's Parax to reproduce the real lens
# cardinals exactly:
#   EFL = 74.9 mm
#   front principal plane = 30.7 mm behind the front vertex
#   rear  principal plane = 30.7 mm ahead of the rear vertex
#   front-to-rear optical-vertex span = 50.0037 mm
#   two-group solve = symmetric (f1=120.584, f2=120.584, d=47.036)
# Because the surrogate is ideal it carries no real aberration -- a traced
# spot is defocus only.  A wired wavefront map (above) augments it with the
# vendor's real OPD; otherwise drop one in beside the STEP to do so.
# Note: Datasheet-only lens: optics derived from the datasheet PDF spec table (no .zmx prescription or Black-Box dump present).
# Note: Optical span = 50 mm (step-body-extent).
# Note: Both principal planes recovered from the datasheet (SF + S'F'); the two ideal groups reproduce all four cardinals exactly.
# Note: Optics derived from the datasheet PDF; no .zmx prescription or Black-Box System/Prescription Data dump was present.

TITLE = 'Machine Vision 0703-005-000-40-EXC'

SETTINGS = {'aperture_type': 'FNO',
 'aperture_value': '8',
 'display_orientation': 'YZ',
 'field_count': 3,
 'field_type': 'Real Image Height',
 'field_value': 41.0,
 'lens_step_axis_offset_xy': [0.0, 0.0],
 'lens_step_largest_component_only': False,
 'lens_step_path': 'attachment/Lens/0703-005-000-40-EXC/0703-005-000-40_PA_a_STEP.stp',
 'lens_step_placement_offset_xyz': [0.0, 0.0, 0.0],
 'lens_step_rotation_x_deg': 0.0,
 'lens_step_rotation_y_deg': 0.0,
 'lens_step_rotation_z_deg': 0.0,
 'object_mode': 'Finite',
 'projection_display_mode': 'Full 3D',
 'show_cardinals': True,
 'wavelength': 0.55}

SURFACES = [{'surface': 'Object',
  'name': 'Object',
  'rc': 0.0,
  'thickness': 119.1,
  'diameter': 82.0,
  'glass': 'AIR'},
 {'surface': 'Standard',
  'name': 'Front Optical Vertex Datum',
  'rc': 0.0,
  'thickness': 1.483859,
  'diameter': 13.1075,
  'glass': 'AIR'},
 {'surface': 'Thin Lens',
  'name': 'Blackbox Group 1',
  'rc': 120.583859,
  'thickness': 23.517991,
  'diameter': 13.1075,
  'glass': 'AIR'},
 {'surface': 'Aperture',
  'name': 'Aperture Stop',
  'rc': 0.0,
  'thickness': 23.517991,
  'diameter': 9.3625,
  'glass': 'AIR'},
 {'surface': 'Thin Lens',
  'name': 'Blackbox Group 2',
  'rc': 120.583859,
  'thickness': 1.483859,
  'diameter': 13.1075,
  'glass': 'AIR'},
 {'surface': 'Standard',
  'name': 'Rear Optical Vertex Datum',
  'rc': 0.0,
  'thickness': 119.1,
  'diameter': 13.1075,
  'glass': 'AIR'},
 {'surface': 'Image',
  'name': 'Image / Sensor',
  'rc': 0.0,
  'thickness': 0.0,
  'diameter': 82.0,
  'glass': 'AIR'}]
