"""Machine-vision lens surrogate generated by folder import."""

# Auto-generated machine-vision lens surrogate (folder import, item 3).
#
# Source prescription : ELS-85 4.5V16K_specification.pdf
# Mechanical STEP     : attachment/Lens/ELS-85-4.5V16K/ELS-85-4.5V16K.STEP
# Datasheet PDF       : ELS-85 4.5V16K_specification.pdf
#
# This is NOT the vendor prescription -- it is a first-order paraxial
# blackbox (two ideal Thin-Lens groups + stop between Front/Rear Optical
# Vertex Datums) solved from KrakenOS's Parax to reproduce the real lens
# cardinals exactly:
#   EFL = 85 mm
#   front principal plane = 33.5985 mm behind the front vertex
#   rear  principal plane = 33.5985 mm ahead of the rear vertex
#   front-to-rear optical-vertex span = 55 mm
#   two-group solve = efl-span-symmetric (f1=137.802, f2=137.802, d=52.2)
# Because the surrogate is ideal it carries no real aberration -- a traced
# spot is defocus only.  A wired wavefront map (above) augments it with the
# vendor's real OPD; otherwise drop one in beside the STEP to do so.
# Note: Datasheet-only lens: optics derived from the datasheet PDF spec table (no .zmx prescription or Black-Box dump present).
# Note: Optical span = 55 mm (step-body-extent).
# Note: Datasheet lists no focal distances; the two ideal groups are a symmetric EFL-equivalent (the principal-plane split is nominal).
# Note: Optics derived from the datasheet PDF; no .zmx prescription or Black-Box System/Prescription Data dump was present.

TITLE = 'Machine Vision ELS-85-4.5V16K'

SETTINGS = {'aperture_type': 'FNO',
 'aperture_value': '4.5',
 'display_orientation': 'YZ',
 'field_count': 3,
 'field_type': 'Real Image Height',
 'field_value': 13.2223,
 'lens_step_axis_offset_xy': [0.0, 0.0],
 'lens_step_largest_component_only': False,
 'lens_step_path': 'attachment/Lens/ELS-85-4.5V16K/ELS-85-4.5V16K.STEP',
 'lens_step_placement_offset_xyz': [0.0, 0.0, 0.0],
 'lens_step_rotation_x_deg': 0.0,
 'lens_step_rotation_y_deg': 0.0,
 'lens_step_rotation_z_deg': 0.0,
 'object_mode': 'Infinity',
 'projection_display_mode': 'Full 3D',
 'show_cardinals': True,
 'wavelength': 0.55}

SURFACES = [{'surface': 'Object',
  'name': 'Object',
  'rc': 0.0,
  'thickness': 100.0,
  'diameter': 26.4445,
  'glass': 'AIR'},
 {'surface': 'Standard',
  'name': 'Front Optical Vertex Datum',
  'rc': 0.0,
  'thickness': 1.4,
  'diameter': 26.4445,
  'glass': 'AIR'},
 {'surface': 'Thin Lens',
  'name': 'Blackbox Group 1',
  'rc': 137.801515,
  'thickness': 26.1,
  'diameter': 26.4445,
  'glass': 'AIR'},
 {'surface': 'Aperture',
  'name': 'Aperture Stop',
  'rc': 0.0,
  'thickness': 26.1,
  'diameter': 18.8889,
  'glass': 'AIR'},
 {'surface': 'Thin Lens',
  'name': 'Blackbox Group 2',
  'rc': 137.801515,
  'thickness': 1.4,
  'diameter': 26.4445,
  'glass': 'AIR'},
 {'surface': 'Standard',
  'name': 'Rear Optical Vertex Datum',
  'rc': 0.0,
  'thickness': 51.401515,
  'diameter': 26.4445,
  'glass': 'AIR'},
 {'surface': 'Image',
  'name': 'Image / Sensor',
  'rc': 0.0,
  'thickness': 0.0,
  'diameter': 26.4445,
  'glass': 'AIR'}]
